package pl.mps.tokenio.sandbox.model.transaction;

public enum TransactionStatus {
    SUCCESS, PENDING_EXTERNAL_AUTHORIZATION, FAILURE_CANCELED, FAILURE_INSUFFICIENT_FUNDS, FAILURE_PERMISSION_DENIED, FAILURE_EXPIRED, FAILURE_DECLINED, FAILURE_GENERIC, PROCESSING, SENT, INITIATED, SETTLEMENT_IN_PROGRESS, SETTLEMENT_COMPLETED, SETTLEMENT_INCOMPLETE
}
